version: '3.4'
services:
    routinator:
        image: nlnetlabs/routinator:latest
        container_name: routinator
        restart: unless-stopped
        networks:
            - artemis
        ports:
            - 3323:3323
            - 8323:8323
        volumes:
            - ./routinator:/home/routinator/.rpki-cache/tals