#
# ARTEMIS Configuration File (FORTH NETWORK)
#
# Start of Prefix Definitions
prefixes:
  cmc_prefix_ipv4: &cmc_prefix_ipv4
  - 119.82.128.0/20^24-24
  - 124.158.0.0/20^24-24
  - 144.48.24.0/22^24-24
  - 183.91.0.0/19^24-24
  - 202.134.16.0/21^24-24
  - 203.171.16.0/20^24-24
  - 203.205.0.0/18^24-24
  - 45.122.232.0/22^24-24
  - 45.122.236.0/22^24-24
  - 45.122.240.0/22^24-24
  - 45.122.244.0/22^24-24
  - 45.122.248.0/22^24-24
  - 45.122.252.0/22^24-24
  - 42.96.32.0/19^24-24
  vnnic_prefix_ipv4: &vnnic_prefix_ipv4
  - 203.119.8.0/22^24-24
  - 203.119.72.0/22^24-24
  - 203.119.64.0/22^24-24
  - 203.119.44.0/22^24-24
  - 203.119.36.0/22^24-24
  # new v4 prefix observed, need to be verified with FORTH
  forth_prefix_v4_new: &forth_prefix_v4_new
  - 192.67.249.0/24
  # new v6 prefix observed, need to be verified with FORTH
  forth_prefix_v6_new: &forth_prefix_v6_new
  - 2001:648:2c30::/48
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
  riperis: [rrc00, rrc01, rrc02, rrc03, rrc04, rrc05, rrc06, rrc07, rrc10, rrc11,
    rrc12, rrc13, rrc14, rrc15, rrc16, rrc18, rrc19, rrc20, rrc21, rrc22, rrc23, rrc24,
    rrc25, rrc26]
  bgpstreamlive:
  - routeviews
  - ris
  bgpstreamkafka:
    host: bmp.bgpstream.caida.org
    port: 9092
    topic: '^openbmp\.router--.+\.peer-as--.+\.bmp_raw'
  bgpstreamhist: '/etc/artemis/'
# End of Monitor Definitions

autoignore:
  autoignore_non_important_prefixes:
    thres_num_peers_seen: 2
    thres_num_ases_infected: 3
    interval: 3600
    prefixes:
    - *cmc_prefix_ipv4
    - *vnnic_prefix_ipv4

# Start of ASN Definitions
asns:
  cmc_asn: &cmc_asn
  - 45903
  - 38732
  - 38733
  vnnic_asn: &vnnic_asn
  - 23902
  - 131415
  - 24066
  viettel_asn: &viettel_asn
  - 7552
  - 24086
  - 38731
  vnpt_asn: &vnpt_asn
  - 45899
  - 7643
  - 135905
  tier_1_asn: &tier_1_asn
  - 2914
# End of ASN Definitions

# Start of Rule Definitions
rules:

- prefixes:
  - *cmc_prefix_ipv4
  origin_asns:
  - *cmc_asn
  neighbors:
  - *tier_1_asn
  - *viettel_asn
  - *vnpt_asn
  mitigation: manual

- prefixes:
  - *vnnic_prefix_ipv4
  origin_asns:
  - *vnnic_asn
  neighbors:
  - *viettel_asn
  - *vnpt_asn
  mitigation: manual

# End of Rule Definitions
