#
# ARTEMIS Configuration File (FORTH NETWORK)
#
# Start of Prefix Definitions
prefixes:
  forth_prefix_main: &forth_prefix_main
  - 139.91.250.0/24
# End of Prefix Definitions

# Start of Monitor Definitions
monitors: {}
  #riperis: ['']
  #bgpstreamlive:
  #- routeviews
  #- ris
  #bgpstreamkafka:
  #  host: bmp.bgpstream.caida.org
  #  port: 9092
  #  topic: '^openbmp\.router--.+\.peer-as--.+\.bmp_raw'
  #bgpstreamhist: '/etc/artemis/'
# End of Monitor Definitions

autoignore:
  autoignore_non_important_prefixes:
    thres_num_peers_seen: 2
    thres_num_ases_infected: 3
    interval: 3600
    prefixes:
    - *forth_prefix_main

# Start of ASN Definitions
asns:
  forth_asn: &forth_asn
  - 8522
  grnet_forth_upstream: &grnet_forth_upstream
  - 5408
# End of ASN Definitions

# Start of Rule Definitions
rules:

- prefixes:
  - *forth_prefix_main
  origin_asns:
  - *forth_asn
  neighbors:
  - *grnet_forth_upstream
  mitigation: manual

# End of Rule Definitions
